### ISSUE TITLE
Don't do Firebase...

### ISSUE THREAD

**Issue by LKO-NCA** [novid20org/novid20-iOS-sdk#1]
Please stop using Firebase...Google isn't the best solution for this.
What about blockchain?

**Comment by eldesouky** [comment]
Thank you for comment.

Firebase was only an app-specific layer that is not used in the SDK. Now, this layer is sliced out of the SDK.

Not sure what do u mean with the blockchain question. This project is not related to blockchain in any way, could you please clarify?

**Comment by LKO-NCA** [comment]
Then how will you save the data?

**Comment by eldesouky** [comment]
We use Coredata and store only on the device. No firebase used on SDK layer

**Comment by LKO-NCA** [comment]
Then how do you sync between users? Will the backend also be open source?

**Comment by eldesouky** [comment]
This project is only the client parts.
 Data is only uploaded from the app hosting the SDK when someone states that he is infected. Then sync happens on the backend side and users at risk will be informed.
Backend is planned to be opensource, but that needs more time. We started with open-sourcing the client-side first as that is the more challenging part.

**Comment by eldesouky** [comment]
As its a clarification and currently no further inquires requested, will close this issue.
Please feel free to open a new issue and share your inquiries or thoughts whenever needed.
