### ISSUE TITLE
Credentials in source code

### ISSUE THREAD

**Issue by greenzeal** [novid20org/novid20-iOS-sdk#2]
Hey friends! 
you have credentials in the source code 
https://github.com/novid20org/novid20-iOS-sdk/blob/master/Example/novid20Proximity/AppDelegate.swift

I would suggest to remove them and leave placeholders.

**Comment by eldesouky** [comment]
Hey Friend,

Thanks a lot for your comment and heads up. The value of those params was already set to the demo app credentials and not the private ones, but the name of the params was having wrong app-specific names. This now has been fixed.

Thanks a lot for mentioning it.

**Comment by eldesouky** [comment]
As the concern is covered, I will close this issue.
Please feel free to open a new issue and share your inquiries or thoughts whenever needed.
